from __future__ import annotations


def export_runtime_config_for_storage(context: dict) -> dict:
    return {
        "proxy_api_key_records": context["proxy_api_key_records"],
        "pools": context["proxy_pools"],
        "model_aliases_text": context["model_aliases_text"],
        "model_capabilities_text": context["model_capabilities_text"],
        "request_timeout": context["request_timeout"],
        "stream_first_event_timeout_seconds": context["stream_first_event_timeout_seconds"],
        "force_upstream_chat_stream": context["force_upstream_chat_stream"],
        "enable_request_normalization": context["enable_request_normalization"],
        "max_completion_tokens": context["max_completion_tokens"],
        "inject_zh_system_prompt": context["inject_zh_system_prompt"],
        "proxy_system_prompt_zh": context["ensure_proxy_prompt_rules"](context["proxy_system_prompt_zh"]),
        "max_retries": context["max_retries"],
        "retry_backoff_ms": context["retry_backoff_ms"],
        "retry_max_backoff_ms": context["retry_max_backoff_ms"],
        "route_switch_window_seconds": context["route_switch_window_seconds"],
        "randomize_endpoints": context["randomize_endpoints"],
        "image_upstream_protocol": context["image_upstream_protocol"],
        "image_task_poll_timeout_seconds": context["image_task_poll_timeout_seconds"],
        "image_task_poll_interval_seconds": context["image_task_poll_interval_seconds"],
        "enable_model_probe": context["enable_model_probe"],
        "model_probe_timeout_seconds": context["model_probe_timeout_seconds"],
        "model_probe_ttl_seconds": context["model_probe_ttl_seconds"],
        "model_route_cache_ttl_seconds": context["model_route_cache_ttl_seconds"],
        "request_cache_ttl_seconds": context["request_cache_ttl_seconds"],
        "enable_interruption_resume": context["enable_interruption_resume"],
        "interruption_resume_ttl_seconds": context["interruption_resume_ttl_seconds"],
        "interruption_resume_max_chars": context["interruption_resume_max_chars"],
        "interruption_resume_min_chars": context["interruption_resume_min_chars"],
        "interruption_resume_enabled": context["enable_interruption_resume"],
        "enable_model_candidate_race": context["enable_model_candidate_race"],
        "model_candidate_race_limit": context["model_candidate_race_limit"],
        "model_candidate_race_timeout_seconds": context["model_candidate_race_timeout_seconds"],
    }


def build_runtime_config_payload(context: dict) -> dict:
    pools = context["proxy_pools"]
    upstream_urls = list(context["upstream_urls"])
    proxy_api_keys = [context["public_proxy_api_key_record"](record) for record in context["proxy_api_key_records"]]
    return {
        "upstream_url": context["upstream_url"],
        "upstream_urls": upstream_urls,
        "upstream_urls_text": "\n".join(upstream_urls),
        "upstream_api_key_configured": False,
        "upstream_api_key_preview": "",
        "proxy_api_keys": proxy_api_keys,
        "proxy_api_key_count": len(proxy_api_keys),
        "proxy_api_key_enabled_count": sum(1 for item in proxy_api_keys if item.get("enabled", True)),
        "proxy_api_key_env_count": context["proxy_api_key_env_count"],
        "pools": pools,
        "pools_count": len(pools),
        "pools_enabled_count": sum(1 for p in pools if p.get("enabled", True)),
        "model_aliases_text": context["model_aliases_text"],
        "model_alias_count": context["model_alias_count"],
        "model_capabilities_text": context["model_capabilities_text"],
        "model_capability_count": context["model_capability_count"],
        "request_timeout": context["request_timeout"],
        "stream_first_event_timeout_seconds": context["stream_first_event_timeout_seconds"],
        "force_upstream_chat_stream": context["force_upstream_chat_stream"],
        "enable_request_normalization": context["enable_request_normalization"],
        "max_completion_tokens": context["max_completion_tokens"],
        "inject_zh_system_prompt": context["inject_zh_system_prompt"],
        "proxy_system_prompt_zh": context["ensure_proxy_prompt_rules"](context["proxy_system_prompt_zh"]),
        "max_retries": context["max_retries"],
        "retry_backoff_ms": context["retry_backoff_ms"],
        "retry_max_backoff_ms": context["retry_max_backoff_ms"],
        "route_switch_window_seconds": context["route_switch_window_seconds"],
        "randomize_endpoints": context["randomize_endpoints"],
        "image_upstream_protocol": context["image_upstream_protocol"],
        "image_task_poll_timeout_seconds": context["image_task_poll_timeout_seconds"],
        "image_task_poll_interval_seconds": context["image_task_poll_interval_seconds"],
        "enable_model_probe": context["enable_model_probe"],
        "model_probe_timeout_seconds": context["model_probe_timeout_seconds"],
        "model_probe_ttl_seconds": context["model_probe_ttl_seconds"],
        "model_route_cache_ttl_seconds": context["model_route_cache_ttl_seconds"],
        "request_cache_ttl_seconds": context["request_cache_ttl_seconds"],
        "enable_interruption_resume": context["enable_interruption_resume"],
        "interruption_resume_ttl_seconds": context["interruption_resume_ttl_seconds"],
        "interruption_resume_max_chars": context["interruption_resume_max_chars"],
        "interruption_resume_min_chars": context["interruption_resume_min_chars"],
        "interruption_resume_enabled": context["enable_interruption_resume"],
        "enable_model_candidate_race": context["enable_model_candidate_race"],
        "model_candidate_race_limit": context["model_candidate_race_limit"],
        "model_candidate_race_timeout_seconds": context["model_candidate_race_timeout_seconds"],
        "config_path": str(context["config_path"]),
        "config_file_exists": context["config_file_exists"],
        "primary_config_path": str(context.get("primary_config_path") or context["config_path"]),
        "config_candidate_paths": [str(item) for item in (context.get("config_candidate_paths") or [])],
        "db_label": context["db_label"],
        "db_enabled": context["db_enabled"],
        "config_source": str(context.get("config_source") or ""),
    }
